# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-add136c9-32f6-4ea8-ab75-4e51d862101e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-add136c9-32f6-4ea8-ab75-4e51d862101e".device = "/dev/disk/by-uuid/add136c9-32f6-4ea8-ab75-4e51d862101e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D012-AF00";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-fb9f8bcc-99ae-4ec7-ae30-d86a8b79fc35"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
